### ISSUE TITLE
MoonCake:new() vs. MoonCake()

### ISSUE THREAD

**Issue by bakpakin** [cyrilis/luvit-mooncake#2]
The former worked for me, while the latter didn't. According to your documentation, MoonCake() should create a new server.

**Comment by cyrilis** [comment]
@bakpakin Sorry, My bad. 

Updating readme now. 

As we know, Lua does not have a class system,  the former version is written in [Moonscript](http://moonscript.org/), which provide a `class`, but the compiled lua syntax is a little complicated, and then I realized luvit has a build in [**`core`**](https://github.com/luvit/luvit/wiki/API#coreobject) which can act like `class` things, so I changed to use `core`.

Please let me know If you have further question, and if you have any question while using this project, feel free to create issue or even pull-request. Thanks! :smile:
